version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: vsa-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: ..
    container_name: vsa-api
    depends_on:
      redis:
        condition: service_healthy
    command:
      - "--http_addr=0.0.0.0:8080"
      - "--persistence_adapter=redis"
      - "--redis_addr=redis:6379"
      - "--rate_limit=1000000"
      - "--commit_threshold=10"
      - "--commit_interval=100ms"
      - "--churn_metrics=false"
    ports:
      - "8080:8080"

# Optional services for future use (disabled by default). Enable with `--profile`.
#profiles:
#  - kafka
#  - postgres

#services:
#  kafka:
#    image: bitnami/kafka:3
#    container_name: vsa-kafka
#    environment:
#      - KAFKA_ENABLE_KRAFT=yes
#      - KAFKA_CFG_PROCESS_ROLES=broker,controller
#      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
#      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
#    ports:
#      - "9092:9092"
#
#  postgres:
#    image: postgres:16-alpine
#    container_name: vsa-postgres
#    environment:
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_DB=vsa
#    ports:
#      - "5432:5432"
