name: Basic CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      - name: Build
        run: go build $(go list ./... | grep -vE '/test/e2e($|/)')

      - name: Run tests
        run: go test -v $(go list ./... | grep -vE '/test/e2e($|/)')

      - name: Run race detector
        run: go test -race -v $(go list ./... | grep -vE '/test/e2e($|/)')
